# Configure Frontend Script (PowerShell)
# This script fetches the API URL from the deployed stack and creates .env.production

$ErrorActionPreference = "Stop"

Write-Host "⚙️  Configuring frontend environment..." -ForegroundColor Cyan

# Check if AWS CLI is installed
try {
    aws --version | Out-Null
} catch {
    Write-Host "❌ AWS CLI is not installed. Please install it first." -ForegroundColor Red
    exit 1
}

# Get the API URL from stack outputs
Write-Host "📋 Fetching API URL from stack..." -ForegroundColor Cyan

$apiUrl = aws cloudformation describe-stacks `
    --stack-name PriceComparisonStack `
    --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" `
    --output text

if ([string]::IsNullOrEmpty($apiUrl)) {
    Write-Host "❌ Failed to fetch API URL. Make sure the stack is deployed." -ForegroundColor Red
    exit 1
}

Write-Host "✅ API URL: $apiUrl" -ForegroundColor Green

# Create .env.production file
$envContent = @"
# Production Environment Variables
# Auto-generated by configure-frontend.ps1

# API Gateway URL
VITE_API_BASE_URL=$apiUrl
"@

$envPath = "frontend\.env.production"
Set-Content -Path $envPath -Value $envContent

Write-Host "✅ Created $envPath" -ForegroundColor Green
Write-Host "🎉 Frontend configuration complete!" -ForegroundColor Green
