#!/bin/bash

# Configure Frontend Script
# This script fetches the API URL from the deployed stack and creates .env.production

set -e

echo "⚙️  Configuring frontend environment..."

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI is not installed. Please install it first."
    exit 1
fi

# Get the API URL from stack outputs
echo "📋 Fetching API URL from stack..."

API_URL=$(aws cloudformation describe-stacks \
    --stack-name PriceComparisonStack \
    --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
    --output text)

if [ -z "$API_URL" ]; then
    echo "❌ Failed to fetch API URL. Make sure the stack is deployed."
    exit 1
fi

echo "✅ API URL: $API_URL"

# Create .env.production file
cat > frontend/.env.production << EOF
# Production Environment Variables
# Auto-generated by configure-frontend.sh

# API Gateway URL
VITE_API_BASE_URL=$API_URL
EOF

echo "✅ Created frontend/.env.production"
echo "🎉 Frontend configuration complete!"
